/* Automatically generated by configure - do not modify */
#define ARCH_ARMV4L 1
#define TUNECPU generic
#define HAVE_LOCALTIME_R 1
#define HAVE_VHOOK 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_MPEGAUDIO_HP 1
#define CONFIG_VIDEO4LINUX 1
#define CONFIG_DV1394 1
#define CONFIG_HAVE_DLOPEN 1
#define CONFIG_HAVE_DLFCN 1
#define CONFIG_AUDIO_OSS 1
#define CONFIG_FTMCP100_CODEC 1
#define HAVE_MALLOC_H 1
//#define HAVE_MEMALIGN 1
#define SIMPLE_IDCT 1
#define CONFIG_RISKY 1
//#define restrict __restrict__

//#define ARRAY_NO_MALLOC

