/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whhcxw_androidcamera_NetEncoder */

#ifndef _Included_Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder
#define _Included_Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whhcxw_androidcamera_AudioPlaybak
 * Method:    registAudioPlay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_AudioPlaybak_registAudioPlay
  (JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetCameraService_registAudioPlay
  (JNIEnv *, jobject);

/*
 * Class:     com_whhcxw_androidcamera_NetEncoder
 * Method:    setVideoFormat
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder_setVideoFormat
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_whhcxw_androidcamera_NetEncoder
 * Method:    setSign
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder_setSign
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_whhcxw_androidcamera_NetEncoder
 * Method:    setServer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder_setServer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_whhcxw_androidcamera_NetEncoder
 * Method:    startWork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder_startWork
  (JNIEnv *, jobject,jboolean);

/*
 * Class:     com_whhcxw_androidcamera_NetEncoder
 * Method:    stopWork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder_stopWork
  (JNIEnv *, jobject);

/*
 * Class:     com_whhcxw_androidcamera_NetEncoder
 * Method:    addFrame
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder_addFrame
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_whhcxw_androidcamera_NetEncoder
 * Method:    addAudioFrame
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder_addAudioFrame
  (JNIEnv *, jobject, jint, jbyteArray);

JNIEXPORT jint JNICALL Java_cx_mobilechecksh_mvideo_androidcamera_NetEncoder_setVideoDesc
  (JNIEnv *, jobject, jint, jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
